# Be sure to restart your server when you modify this file.

# Add new mime types for use in respond_to blocks:
# Mime::Type.register "text/richtext", :rtf
# Mime::Type.register_alias "text/html", :iphone

extension_map = {
  # Text Types
  ".asc" => "text/plain",
  ".c" => "text/plain",
  ".cc" => "text/plain",
  ".cpp" => "text/plain",
  # ".css" => "text/css",
  # ".csv" => "text/csv",
  ".dsl" => "text/dsssl",
  ".dsssl" => "text/dsssl",
  ".etx" => "text/x-setext",
  ".f" => "text/plain",
  ".f90" => "text/plain",
  ".h" => "text/plain",
  ".hh" => "text/plain",
  # ".htm" => "text/html",
  # ".html" => "text/html",
  ".lsp" => "text/plain",
  ".m" => "text/plain",
  ".pl" => "text/plain",
  ".py" => "text/plain",
  ".rb" => "text/plain",
  ".rtf" => "text/rtf",
  ".rtx" => "text/richtext",
  ".sgm" => "text/sgml",
  ".sgml" => "text/sgml",
  ".tsv" => "text/tab-separated-values",
  ".txt" => "text/plain",
  # ".text" => "text/plain",

  # Application Types
  ".a" => "application/octet-stream",
  ".ai" => "application/octet-stream",
  # ".atom" => "application/atom+xml",
  ".bcpio" => "application/x-bcpio",
  ".bin" => "application/octet-stream",
  ".ccad" => "application/clariscad",
  ".cdf" => "application/x-netcdf",
  ".class" => "application/octet-stream",
  ".cpio" => "application/x-cpio",
  ".cpt" => "application/mac-compactpro",
  ".csh" => "application/x-csh",
  ".dcr" => "application/x-director",
  ".dir" => "application/x-director",
  ".dll" => "application/octet-stream",
  ".dms" => "application/octet-stream",
  ".doc" => "application/msword",
  ".drw" => "application/drafting",
  ".dvi" => "application/x-dvi",
  ".dwg" => "application/acad",
  ".dxf" => "application/dxf",
  ".dxr" => "application/x-director",
  ".dylib" => "application/octet-stream",
  ".eps" => "application/postscript",
  ".exe" => "application/octet-stream",
  ".ez" => "application/andrew-inset",
  ".gtar" => "application/x-gtar",
  ".gz" => "application/x-gzip",
  ".hdf" => "application/x-hdf",
  ".hqx" => "application/mac-binhex40",
  ".ips" => "application/x-ipscript",
  ".ipx" => "application/x-ipix",
  # ".js" => "application/javascript",
  ".latex" => "application/x-latex",
  ".lha" => "application/octet-stream",
  ".ltx" => "application/x-latex",
  ".lzh" => "application/octet-stream",
  ".man" => "application/x-troff-man",
  ".me" => "application/x-troff-me",
  ".mif" => "application/vnd.mif",
  ".ms" => "application/x-troff-ms",
  ".nc" => "application/x-netcdf",
  ".oda" => "application/oda",
  ".pdf" => "application/pdf",
  ".pgn" => "application/x-chess-pgn",
  ".pot" => "application/mspowerpoint",
  ".pps" => "application/mspowerpoint",
  ".ppt" => "application/mspowerpoint",
  ".ppz" => "application/mspowerpoint",
  ".pre" => "application/x-freelance",
  ".prt" => "application/pro_eng",
  ".ps" => "application/postscript",
  ".roff" => "application/x-troff",
  # ".rss" => "application/rss+xml",
  ".rss09" => "application/rdf+xml",
  ".rss10" => "application/rdf+xml",
  ".rss11" => "application/rdf+xml",
  ".rss20" => "application/rss+xml",
  ".scm" => "application/x-lotusscreencam",
  # ".set" => "application/set",
  ".sh" => "application/x-sh",
  ".shar" => "application/x-shar",
  ".sit" => "application/x-stuffit",
  ".skd" => "application/x-koan",
  ".skm" => "application/x-koan",
  ".skp" => "application/x-koan",
  ".skt" => "application/x-koan",
  ".smi" => "application/smil",
  ".smil" => "application/smil",
  ".so" => "application/octet-stream",
  ".sol" => "application/solids",
  ".spl" => "application/x-futuresplash",
  ".src" => "application/x-wais-source",
  ".step" => "application/STEP",
  ".stl" => "application/SLA",
  ".stp" => "application/STEP",
  ".sv4cpio" => "application/x-sv4cpio",
  ".sv4crc" => "application/x-sv4crc",
  ".swf" => "application/x-shockwave-flash",
  ".t" => "application/x-troff",
  ".tar" => "application/x-tar",
  ".tcl" => "application/x-tcl",
  ".tex" => "application/x-tex",
  ".texi" => "application/x-texinfo",
  ".texinfo" => "application/x-texinfo",
  ".tr" => "application/x-troff",
  ".tsp" => "application/dsptype",
  ".unv" => "application/i-deas",
  ".ustar" => "application/x-ustar",
  ".vcd" => "application/x-cdlink",
  ".vda" => "application/vda",
  ".xlc" => "application/vnd.ms-excel",
  ".xll" => "application/vnd.ms-excel",
  ".xlm" => "application/vnd.ms-excel",
  ".xls" => "application/vnd.ms-excel",
  ".xlw" => "application/vnd.ms-excel",
  # ".xml" => "application/xml",
  ".xsl" => "application/xml",
  ".zip" => "application/zip",

  # Image Types
  ".ief" => "image/ief",
  ".g3f" => "image/g3fax",
  ".gif" => "image/gif",
  ".jpe" => "image/jpeg",
  ".jpeg" => "image/jpeg",
  ".jpg" => "image/jpeg",
  ".pbm" => "image/x-portable-bitmap",
  ".pct" => "image/x-pict",
  ".pgm" => "image/x-portable-graymap",
  ".pic" => "image/x-pict",
  ".pict" => "image/x-pict",
  ".png" => "image/png",
  ".pnm" => "image/x-portable-anymap",
  ".ppm" => "image/x-portable-pixmap",
  ".ras" => "image/x-cmu-raster",
  ".rast" => "image/x-cmu-raster",
  ".rgb" => "image/x-rgb",
  ".tif" => "image/tiff",
  ".tiff" => "image/tiff",
  ".xbm" => "image/x-xbitmap",
  ".xpm" => "image/x-xpixmap",
  ".xwd" => "image/x-xwindowdump",

  # Audio Types
  ".aif" => "audio/x-aiff",
  ".aifc" => "audio/x-aiff",
  ".aiff" => "audio/x-aiff",
  ".au" => "audio/basic",
  ".kar" => "audio/midi",
  ".mid" => "audio/midi",
  ".midi" => "audio/midi",
  ".mp2" => "audio/mpeg",
  ".mp3" => "audio/mpeg",
  ".mpga" => "audio/mpeg",
  ".ra" => "audio/x-realaudio",
  ".ram" => "audio/x-pn-realaudio",
  ".rm" => "audio/x-pn-realaudio",
  ".rpm" => "audio/x-pn-realaudio-plugin",
  ".snd" => "audio/basic",
  ".tsi" => "audio/TSP-audio",
  ".wav" => "audio/x-wav",
  ".wma" => "audio/wma",

  # Video Types
  ".avi" => "video/avi",
  ".fli" => "video/x-fli",
  ".mov" => "video/quicktime",
  ".movie" => "video/x-sgi-movie",
  ".mp2v" => "video/mpeg-2",
  ".mpe" => "video/mpeg",
  ".mpeg" => "video/mpeg",
  ".mpg" => "video/mpeg",
  ".mpv2" => "video/mpeg-2",
  ".qt" => "video/quicktime",
  ".viv" => "video/vnd.vivo",
  ".vivo" => "video/vnd.vivo",
  ".wmv" => "video/wmv",

  # Other Types
  ".ice" => "x-conference/x-cooltalk",
  ".iges" => "model/iges",
  ".igs" => "model/iges",
  ".mesh" => "model/mesh",
  ".mime" => "www/mime",
  ".msh" => "model/mesh",
  ".pdb" => "chemical/x-pdb",
  ".silo" => "model/mesh",
  ".vrml" => "model/vrml",
  ".wrl" => "model/vrml",
  ".xyz" => "chemical/x-pdb"
}
      
extension_map.each do |ext,value|
  Mime::Type.register value, ext[1..ext.length].to_sym
end
